#!/usr/bin/env bash
cat << EOF > /etc/environment
MUTTER_DEBUG_FORCE_KMS_MODE=simple
MUTTER_DEBUG_KMS_THREAD_TYPE=user
# GNOME_SHELL_SLOWDOWN_FACTOR=0.8
LIBGL_KOPPER_DRI2=1
# __GLX_VENDOR_LIBRARY_NAME=mesa
MESA_LOADER_DRIVER_OVERRIDE=zink
GALLIUM_DRIVER=zink 
GSK_RENDERER=vulkan
FLATPAK_GL_DRIVERS=mesa-git
EOF
