[language-server.rust-analyzer.config]
check = {command = "clippy", extraArgs = ["--", "-W", "clippy::all", "-W", "clippy::pedantic", "-W", "clippy::nursery", "-W", "clippy::cargo"]}

[[language]]
name = "typescript"
language-id = "typescript"
scope = "source.ts"
injection-regex = "^(ts|typescript)$"
file-types = ["ts"]
shebangs = ["deno"]
roots = ["deno.json", "deno.jsonc", "package.json"]
auto-format = true
language-servers = ["deno-lsp"]

[language-server.deno-lsp]
command = "deno"
args = ["lsp"]

[language-server.deno-lsp.config.deno]
enable = true

[[language]]
name = "html"
formatter = { command = "prettier" }
language-servers = [ "vscode-html-language-server", "tailwindcss-ls" ]

[[language]]
name = "css"
formatter = { command = "prettier" }
language-servers = [ "vscode-css-language-server", "tailwindcss-ls" ]

[[language]]
name = "jsx"
formatter = { command = "prettier" }
language-servers = [ "deno-lsp", "tailwindcss-ls" ]

[[language]]
name = "tsx"
formatter = { command = "prettier" }
language-servers = [ "deno-lsp", "tailwindcss-ls" ]

[[language]]
name = "svelte"
formatter = { command = "prettier" }
language-servers = [ "svelteserver", "tailwindcss-ls" ]

[[language]]
name = "vue"
auto-format = true
formatter = { command = "prettier", args = ["--parser", "vue"] }
language-servers = ["typescript-language-server"]

[[language-server.typescript-language-server.config.plugins]]
name = "@vue/typescript-plugin"
location = "/home/tulili/.bun/install/global/node_modules/@vue/language-server"
languages = ["vue"]
